### ISSUE TITLE
Packaging of the app occurs before downloading dependencies

### ISSUE THREAD

**Issue by cdbartholomew** [LangStream/langstream#187]
I created a pipeline that requires the C* sink, like this:

```
 - name: "Write to AstraDB"
    type: "sink"
    input: "text-chunks"
    configuration:
      connector.class: com.datastax.oss.kafka.sink.CassandraSinkConnector
      key.converter: org.apache.kafka.connect.storage.StringConverter
      value.converter: org.apache.kafka.connect.storage.StringConverter
      cloud.secureConnectBundle: "{{{ secrets.cassandra.secure-connect-bundle }}}"
      auth.username: "{{{ secrets.cassandra.username }}}"
      auth.password: "{{{ secrets.cassandra.password }}}"
      topic.chunks-topic.documents.documents.mapping: "filename=value.filename, chunk_id=value.chunk_id, language=value.language, text=value.text, embeddings_vector=value.embeddings_vector, num_tokens=value.chunk_num_tokens"
      name: cassandra-sink
```
And this:
```
configuration:
  resources:
  - type: "open-ai-configuration"
    name: "OpenAI Azure configuration"
    configuration:
      url: "{{ secrets.open-ai.url }}"
      access-key: "{{ secrets.open-ai.access-key }}"
      provider: "azure"
  dependencies:
    - name: "Kafka Connect Sink for Apache Cassandra from DataStax"
      url: "https://github.com/datastax/kafka-sink/releases/download/1.5.0/kafka-connect-cassandra-sink-1.5.0.jar"
      sha512sum: "242bf60363d36bd426232451cac836a24ae8d510857372a128f601503ad77aa9eabf14c4f484ca0830b6a68d9e8664e3820739ad8dd3deee2c58e49a94a20a3c"
      type: "java-library"
~
```

The first time I deployed the app, the sink went into a crash loop with a `ClassNotFound` error. I shelled into the pod and noticed that the `java/lib` directory that should contain the jar for the C* sink was not in the `/app-code-download` directory.

I deleted the app and redeployed it. The logs messages look like this:

```
chrisbartholomew@cbartholomew-rmbp16 ~/git/streaming-gen-ai -  (main) $  ./bin/sga-cli --conf=conf/cli.yaml apps deploy i-love-ai -app examples/applications/i-love-ai/ -i examples/instances/astra.yaml -s examples/applications/i-love-ai/secrets.yaml
packaging app: /Users/chrisbartholomew/git/streaming-gen-ai/examples/applications/i-love-ai
app packaged
using instance: /Users/chrisbartholomew/git/streaming-gen-ai/examples/instances/astra.yaml
using secrets: /Users/chrisbartholomew/git/streaming-gen-ai/examples/applications/i-love-ai/secrets.yaml
deploying application: i-love-ai (28633 KB)
Dependency: examples/applications/i-love-ai/java/lib/kafka-connect-cassandra-sink-1.5.0.jar at /Users/chrisbartholomew/git/streaming-gen-ai/examples/applications/i-love-ai/java/lib/kafka-connect-cassandra-sink-1.5.0.jar
application i-love-ai deployed
```
From the logs, it looks like "packaging app" is happening before checking the dependency and downloading it. 

The second time I deployed the app, the C* sink worked and the `java/lib` directory was present.
