### ISSUE TITLE
Webcrawler agent enhancements

### ISSUE THREAD

**Issue by ddieruf** [LangStream/langstream#254]
Currently, the web crawler agent uses Jsoup to:

- Connect to page URL
- Get all href's on the page and add to a crawl queue
- Get the current page's HTML (`document.html()`)
- Create a document from that HTML

Ideally, the agent could offer  more features like:

- Scrape the screen by rendering the page's HTML and create a Document from the text().
    - As a screen scrape it is assumed that no media (img, video, etc) will be included, just simple text.
- Offer a filter by node id or node class
- Offer the option to provide an abstract Jsoup processing function
- Add select page head meta values to the Document header

Example screen scrape starting a certain node id and including a few head meta values
(so only the document's page content is retrieved, not the document navigation href's on every page pass):

```yaml
  - name: "Crawl the WebSite"
    type: "webcrawler-source"
    configuration:
      seed-urls: "https://docs.langstream.ai/"
      allowed-domains: "https://docs.langstream.ai"
      ...
      asHtml: false
      asText: true
      parent-tag-id: "document-main"
      include-head-meta-names: "description, og:title, article:author, og:image"
```

- asHtml could be the default
- If parent-tag-id is not provided then grab the page .body()
- Each <head><meta name="xxxxx"> value will be added as name/value header with the Document

Example custom function:

```yaml
  - name: "Crawl the WebSite"
    type: "webcrawler-source"
    configuration:
      seed-urls: "https://docs.langstream.ai/"
      allowed-domains: "https://docs.langstream.ai"
      ...
      page-render-function: -|
          private string renderPage(Jsoup.Document doc){
              Element ele = doc.body();

              // could do all kinds of weird page navigation

              return ele.text();
          }
```
