### ISSUE TITLE
Cannot use templating for topic names

### ISSUE THREAD

**Issue by cdbartholomew** [LangStream/langstream#310]
I am trying to define topic names using globals defined in the instance file. Here is my configuration in that file:

```
instance:
  globals:
    assistantType: "Indeed documentation"
    vectorKeyspace: "chatbot"
    vectorTable: "indeeddocs"
    chunksTopic: "indeed-chunks"
    questionsTopic: "indeed-questions"
    answersTopic: "indeed-answers"
    logTopic: "indeed-logs"
    seedUrls: "https://docs.indeed.com/"
    allowedUrls: "https://docs.indeed.com/"
```
And this is how I am using the globals for topic names:

```
topics:
  - name: "{{{globals.questionsTopic}}}"
    creation-mode: create-if-not-exists
  - name: "{{{globals.answersTopic}}}"
    creation-mode: create-if-not-exists
  - name: "{{{globals.logTopic}}}"
    creation-mode: create-if-not-exists
errors:
    on-failure: "skip"
pipeline:
  - name: "convert-to-structure"
    id: "convert-to-structure"
    type: "document-to-json"
    input: "{{{globals.questionsTopic}}}"
    configuration:
      text-field: "question"
```
When I deploy this pipeline it creates topic with the variable names, not their values, like this:
![image](https://github.com/LangStream/langstream/assets/22917476/90ca6e24-c05b-4f5f-bcf2-8d6a984eab22)

It doesn't matter if I use 2 or 3 curly brackets, the result is the same.

This actually works to use the strange topic names, but it is not the result I am expecting.
