### ISSUE TITLE
[BUG] document-to-json agent copy-properties option not copying correct value

### ISSUE THREAD

**Issue by ddieruf** [LangStream/langstream#315]
Given this order of pipeline steps

```yaml
  - name: "Split into chunks"
    type: "text-splitter"
    input: html-render
    output: text-split
    configuration:
      splitter_type: "RecursiveCharacterTextSplitter"
      chunk_size: 10
      separators: ["\n\n", "\n", " ", ""]
      keep_separator: false
      chunk_overlap: 3
      length_function: "cl100k_base"

  - name: "Convert to json"
    type: "document-to-json"
    input: text-split
    output: json-text
    configuration:
      text-field: text
      copy-properties: true
```

The properties added by text-splitter are not getting decoded correctly by document-to-json.

Here are the headers added by splitter:
`{ "chunk_text_length": "10", "chunk_id": "4", "chunk_num_tokens": "4" }`

Here is the result after document-to-json:
```
headers: { "chunk_text_length": "21", "chunk_id": "1", "chunk_num_tokens": "4" }
body:
{
  "chunk_text_length": "MjE=",
  "text": "some test text.",
  "chunk_id": "MQ==",
  "chunk_num_tokens": "NA=="
}
```

Notice the numeric values in the body are encoded.
