### ISSUE TITLE
[feature] Add a way to configure init jobs to setup tables on Vector Databases and other resources (implements Assets)

### ISSUE THREAD

**Issue by eolivelli** [LangStream/langstream#353]
Since the beginning of the design of LangStream we thought about adding the concept of "assets".

Now that people are using more and more LS it is clear that setting up third party resources must be handled by the LS application as well.

LS already creates the topics on Kafka/Pulsar but it cannot create the tables on Cassandra or the Indexes on Pinecone/ElastichSeach.

This issue a feature request for implement some kind of "initialisation jobs" that are executed at deployment time:
- when you deploy the application for the first time
- when you update the application
- when you delete the application

But it would be awkward to ask developers to create "jobs", because you have to deal with the state of the resource.
For instance you want to create the table only if it exists.

configuration.yaml

```
assets:
  - type: cassandra-table
     datasource: MyAstraDataSource
     creation-mode: create-if-not-exists|none
     drop-mode: drop-on-undeploy|none
     config:
          tableName: products
          keyspace: vsearch
          statements:
                - "CREATE TABLE products.. .."
                - "CREATE INDEX .... "
  - type: pinecone-index
     datasource: MyPineconeDataSource
     creation-mode: create-if-not-exists|none
     drop-mode: drop-on-undeploy|none
     config:
          indexName: products
          ...
  - type: jdbc-table
     datasource: MyPostGresDataSource
     creation-mode: create-if-not-exists|none
     drop-mode: drop-on-undeploy|none
     config:
          driverClassName: org.postgres.Driver
          tableName: products
          statements:
                - "CREATE TABLE products.. .."
                - "CREATE INDEX .... "
```
