### ISSUE TITLE
Assets don't support mustache templating

### ISSUE THREAD

**Issue by cdbartholomew** [LangStream/langstream#425]
I tried to deploy an application using assets with mustache templating and the templating doesn't seem to be working. This is the error I am seeing:

```
│ setup java.lang.IllegalArgumentException: Illegal character in path at index 91: https://api.astra.datastax.com/v2/databases/dc575250-fc0f-4e0 │
│ e-b168-b42c8572436a/keyspaces/{{ globals.vectorKeyspace}}
```

This is my asset definition:

```
assets:
  - name: "keyspace"
    asset-type: "astra-keyspace"
    creation-mode: create-if-not-exists
    config:
      keyspace: "{{% globals.vectorKeyspace}}"
      datasource: "AstraDatasource"
  - name: "vector-table"
    asset-type: "cassandra-table"
    creation-mode: create-if-not-exists
    config:
      table-name: "{{% globals.vectorTable}}"
      keyspace: "{{% globals.vectorKeyspace}}"
      datasource: "AstraDatasource"
      create-statements:
        - >
          CREATE TABLE IF NOT EXISTS {{% globals.vectorKeyspace}}.{{% globals.vectorTable }} (  
            filename TEXT,
            chunk_id int,
            num_tokens int,
            language TEXT,  
            text TEXT,
            embeddings_vector VECTOR<FLOAT, 1536>,
            PRIMARY KEY (filename, chunk_id)
            );
        - >
          CREATE CUSTOM INDEX IF NOT EXISTS {{% globals.vectorKeyspace}}.{{% globals.vectorIndex }} 
          ON {{% globals.vectorTable }}(embeddings_vector) USING 'StorageAttachedIndex';
```

**Comment by cdbartholomew** [comment]
Actually, I was wrong. Templating does work. It seems like I used invalid template syntax `{{% globals.vectorTable}}`. The extra % appears in some examples and I copied that pattern. If I remove the % the templating seems to work.

I don't really understand the templating language. Reviewing the examples, the % seems to be used when working with the values in the event pipeline. For example:

```
configuration:
      model: "{{{secrets.open-ai.embeddings-model}}}" # This needs to match the name of the model deployment, not the base model
      embeddings-field: "value.embeddings"
      text: "{{% value.name }} {{% value.description }}"
```

I am not sure if this is the rule. I did a quick Google search on the mustache templating and I couldn't find anything about the use of % in a mustache template.
