### ISSUE TITLE
Prompt templates should be pluggable

### ISSUE THREAD

**Issue by devinbost** [LangStream/langstream#432]
There's a growing list of prompt templates that LangStream should be able to leverage. 
For example, FLARE: https://github.com/devinbost/langchain/blob/f35db9f43e2301d63c643e01251739e7dcfb6b3b/libs/langchain/langchain/chains/flare/prompts.py

(Demo with CassIO is here: https://colab.research.google.com/drive/1FGMmmkvy3PH7gWQdBBr05HFLTsM6PRU6)

and many other prompts are available in this directory: https://github.com/devinbost/langchain/tree/b3a8fc7cb17170b8a272a0a1366b0f18d8f7ab4a/libs/langchain/langchain/chains

If we can leverage these pluggably, then we won't need to spend so much time trying to keep up as new research results in additional prompt techniques.

**Comment by eolivelli** [comment]
I think that it is too early to standardize a mechanism to handle prompts, loops and so on.

We need more feedback from the community.

LangChain is trying to build some model around this topic, but we can wait to see this taking more shape.

It would be great to see how people are trying to build this patterns here with LangStream.

Moving from a flat python file to a scalable deployment with async batch processing will be fun and interesting.

**Comment by eolivelli** [comment]
After working a little bit on sample applications and demos I realise that we need to at least make "prompts" a first class object, like we have agents, assents and resources.

Also one big problem is the the prompt format highly depends on two factors:
- the LLM model you are using (some LLMs are very "chatty" and they interact with an human, other LLMs are more formal, like the "instruct" models)
- the LLM API (some LLMS allows you to report some context and examples (like Vertex), other require a list of messages with "roles" (like OpenAI), others only require a simple string (like OpenSource models from Ollama) 

My proposal is to add a new file type that contains prompts and in the chat-completion and text-completion agents you can refer to a prompt by id.

Something like:

prompt1.yaml

```yaml
prompt:
 - id: qa-chatbot-openai-sample-1
   templating-language: mustache
   messages:
         - role: system
            text: |
                    .... .{{documents}}..
        - role: user
          text: {{value.question}}
```

prompt2.yaml

```yaml
prompt:
 - id: qa-chatbot-ollama-sample-1
   templating-language: mustache
   examples:
             .....
    text: |
            .... .{{documents}}..
```

prompt3yaml


```yaml
prompt:
 - id: qa-chatbot-vertex-sample-1
   templating-language: mustache
   examples:
             .....
   messages:
         - role: system
            text: |
                .... .{{documents}}..
        - role: user
          text: {{value.question}}
```
