### ISSUE TITLE
Add an easy way to use LangChain components wiithout writing Python code

### ISSUE THREAD

**Issue by eolivelli** [LangStream/langstream#497]
It is pretty easy to use LangChain, but you still have to write Python code.

There are some APIs that should be easy to integrate without writing code, for instance the DocumentLoader API.
https://python.langchain.com/docs/modules/data_connection/document_loaders/

What about something like

```yaml
pipeline:
   - type: "s3-source"
     .....
   - type: "langchain-documentloader-processor"
     configuration:
         documentLoader: CSVLoader
         params....
     ....    
```

This way LangStream users can use the full power of LangChain without writing any code
