### ISSUE TITLE
Stateful agents: design proposal

### ISSUE THREAD

**Issue by eolivelli** [LangStream/langstream#554]
Feature description:

There is need to build stateful agents with some local disk.
Same applications:
- store "conversational history"
- do simple aggregations
- run Kafka Streams

Ideas:

As we are already using Stateful Set it is pretty simple to provision a disk to each replica and to tie the lifecycle of the disk to the instance.

It is important to notice that in a composite agent pipeline each agent will have its own disk, so we have to deal with it.
Probably a single volume is enough but each agent will have a reference to a specific directory.

It is currently not allowed to change the execution plan in a way that agents that run together are moved to different "executors", so it WOULD be fine to share the disk, 
but on the other side agents may need different types of disk or sizes, so from this observation is seems better to mount a volume per each agent (in the future this will also allow to split an executor into single agents)

 Proposal:

```
pipeline:
   - name: "Stateful agent"
      type: "web-crawler"
      resources:
            disk:
                size: 10MB
                storage-class: default
      configuration:
            ......
```

The planner may decide to request a disk for an agent given the configuration:
```
pipeline:
   - name: "Stateful agent"
      type: "web-crawler"
      configuration:
            persistence: disk
```

This will be mapped by the planner (the WebCrawler node provider) to something like:

```
pipeline:
   - name: "Stateful agent"
      type: "web-crawler"
      resources:
            disk:
                size: some-default-size-for-webcrawler
                storage-class: default-storage-class
      configuration:
            ......
```

It is important that the planner is able to request a disk even if it is not explicitly configured by the user, otherwise the behaviour of the agent may be not safe in production.

We can do that in AbstractAgentProvider, with a method like

```
DiskResourcesSpec computeDiskResourceSpec(
        AgentConfiguration agentConfiguration,
            Module module,
            Pipeline pipeline,
            ExecutionPlan executionPlan,
            ComputeClusterRuntime clusterRuntime) {
       ........
}
```

**Comment by nicoloboschi** [comment]
Some comments:

**Disk parameters**
One problem is about exposing disk parameters. We need to create some abstraction between the user model and the actual pod configuration. Users cannot create storage-classes since they don't know about the underling provider.
In your example there is ´ storage-class: default´ that makes me think that "default" is a storage class defined in langstream and it's not mapped directly to kubernetes storage classes.

So I believe that this would be the conversion flow:
1. The operator configuration defines a set of storage classes and how they're mapped to kubernetes StorageClass model
```
storage-classes:
  - type: fast
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
    provisioner: kubernetes.io/aws-ebs
    reclaimPolicy: Retain
    parameters: 
      type: gp2
      fsType: ext4
```
2. When the operator starts, verify the storage classes are all set up - any update will reflect the storage classes and newly requested disks
3. The user requests an agent to use type: "fast" 
```
pipeline:
   - name: "Stateful agent"
      type: "web-crawler"
      resources:
            disk:
                size: 1GB
                type: fast
      configuration:
```

4. The operator then reads the agent will then apply the storage class when creating the STS   

Probably it's better to have some stereotypes like "fast", "default", "cheap" and not let configure any kind of types otherwise the discovery is very hard to do since it depends on the cluster installation.



**Per agent disk**
Having per-agent disks is far more easier to manage. IMHO Most of the time users will only have one-two stateful agents in the pipeline.
