### ISSUE TITLE
Using syntax value.xx, key.xxx on a primitive schema has no effect

### ISSUE THREAD

**Issue by nicoloboschi** [LangStream/langstream#582]
Example pipeline: 
```
pipeline:
# here is raw string
  - name: "Sample"
    type: "query"
    input: "in-topic"
    configuration:
      datasource: "xx"
      query: "SELECT id from XX"
      output-field: "value.myid"
```

If I send a message to `in-topic` with a raw string, the result of the query is ignored.

This might be expected and the solution is to prepend to `document-to-json` agent. 
But it's very confusing that there's no error/log anywhere and the result is just ignored. 

We should either throw an error (incompatible change) or at least add some logs
