### ISSUE TITLE
Query agent: add support for DML (Data Manipulation Language) statements

### ISSUE THREAD

**Issue by eolivelli** [LangStream/langstream#600]
Feature request:

Currently the "query" (and "query-vector-db") agent is expected to generate a result set (like the JDBC executeQuery).
Sometimes you only want to write to a database: UPDATE/INSERT/DELETE.

The result of the agent may include the "generated values" or the "update count"

**Comment by eolivelli** [comment]
I see two options:
- create a new agent "execute-statement" or something like that
- add a new "mode" parameter to the query agent:

```yaml
pipeline:
     - type: query
       mode: execute-statement
       query: | 
                 INSERT INTO chat_history(sessionId,question,answer) VALUES(?,?,?)
      ......
  
```
Or to maintain the documents database:

```yaml
pipeline:
     - type: query
       mode: execute-statement 
       query: | 
                 DELETE FROM documents WHERE documentId=? and checkId >= ?
      ......
  
```
