### ISSUE TITLE
No AgentCodeProvider found for type python-function

### ISSUE THREAD

**Issue by mhamdik** [LangStream/langstream#671]
Hello,

when I deploy my Python processor agent i have this error:

java.lang.RuntimeException: No AgentCodeProvider found for type python-function.

Agent:
```yaml
  - name: "Process using Python"
    type: "python-function"
    output: "chunks-topic"
    configuration:
      className: embeddings.Embedding
      embeddings-field: "record.embeddings"
      text: "{{ value.text }}"
```

Python processor:
```
class Embedding(object):
    def process(self, record):
        embedding = model.encode(record.value(), convert_to_numpy=True, normalize_embeddings=True)
        result = {"input": str(record.value()), "embedding": embedding.tolist()}
        new_value = json.dumps(result)
        return [SimpleRecord(value=new_value)]
```
<img width="299" alt="Capture d’écran 2023-10-31 à 02 11 42" src="https://github.com/LangStream/langstream/assets/102757172/e1a1e140-f7ed-4c31-a8f2-5f1f6e74e47d">

thanks
