### ISSUE TITLE
RESOURCE_EXHAUSTED in python-source agent

### ISSUE THREAD

**Issue by Dobosz** [LangStream/langstream#744]
Processing large data with `python-source` results in `RESOURCE_EXHAUSTED` error for gRPC:
```
Critical failure: gRPC server sent error: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 11646340. Shutting down the runtime...
```

Perhaps some kind of streaming between python runtime and agent service is in order.

**Comment by eolivelli** [comment]
How much large is your payload?

**Comment by eolivelli** [comment]
Also, what's the next agent in your pipeline? Another python agent or a builtin agent?

**Comment by Dobosz** [comment]
Looks like it's 11646340 (~11MB).
Next one is a build-in agent:
```yaml
  - name: "Extract text"
    id: "extract-text"
    type: "text-extractor"
```
