### ISSUE TITLE
Support GPU in Kubernetes cluster

### ISSUE THREAD

**Issue by ddieruf** [LangStream/langstream#758]
I would like to use the [gpu in my K8s cluster](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/) with my LS application. Could a new feature be added to the `resources` area in the pipeline manifest :

```yaml
...
resources:
  gpu:
    vendor: "gpu-vendor.example/example-gpu"
    count: 1
```

Which would be incorporated into the agent statefulset template, to include the limits spec:

```yaml
...
resources:
  limits:
    gpu-vendor.example/example-gpu: 1
```

Then in my custom python processor, I can do image manipulations and bring in my own models to do fun things :)
